const affirmations = [
    "Hoy me abro a recibir la guía amorosa de mis ángeles.",
    "Soy protegido por la luz divina en cada paso que doy.",
    "Confío en que el universo tiene un plan perfecto para mí.",
    "Mi ángel de la guarda susurra palabras de paz en mi corazón.",
    "La abundancia fluye hacia mí por gracia divina.",
    "Soy un canal de amor y luz para el mundo.",
    "Libero mis miedos y los entrego a los ángeles para su transmutación.",
    "Cada desafío es una oportunidad de crecimiento espiritual.",
    "La sabiduría de los arcángeles ilumina mi mente hoy.",
    "Siento la presencia reconfortante de mis guías celestiales.",
    "Mi hogar está rodeado de una esfera de protección angélica.",
    "Soy digno de todas las bendiciones que el cielo me envía.",
    "Abro mi corazón para perdonar y ser perdonado.",
    "La paz de Dios habita en mi interior y se refleja en mi vida.",
    "Mis palabras hoy son inspiradas por la bondad divina.",
    "Confío en mi intuición, es la voz de mis ángeles guiándome.",
    "Suelto el control y permito que los milagros ocurran.",
    "La alegría es mi estado natural de ser.",
    "Soy amado incondicionalmente por la Fuente Creativa.",
    "Mis sueños están bajo la custodia de los ángeles del sueño.",
    "Hoy elijo ver la belleza en cada persona que encuentro.",
    "La fuerza del Arcángel Miguel me da valor para superar obstáculos.",
    "La sanación del Arcángel Rafael restaura mi cuerpo y alma.",
    "La claridad del Arcángel Gabriel guía mis comunicaciones.",
    "La abundancia del Arcángel Uriel me provee de todo lo necesario.",
    "Soy una creación perfecta de la Inteligencia Divina.",
    "Mi vida es un reflejo de la armonía celestial.",
    "Agradezco por las pequeñas señales que mis ángeles me envían.",
    "Hoy es un día lleno de sincronicidades positivas.",
    "Mi fe es más fuerte que cualquier duda.",
    "El amor divino disuelve toda barrera en mi camino.",
    "Soy un faro de esperanza para quienes me rodean.",
    "Mis finanzas están bendecidas y se multiplican con propósito.",
    "La paciencia es una virtud que cultivo con ayuda divina.",
    "Entrego mis preocupaciones al cielo y descanso en paz.",
    "Soy libre de las cargas del pasado.",
    "Mi futuro es brillante y lleno de promesas divinas.",
    "Cada respiración me conecta más profundamente con mi espíritu.",
    "La luz de los ángeles disipa cualquier sombra en mi mente.",
    "Soy un imán para la gente positiva y las buenas oportunidades.",
    "Mi cuerpo es un templo sagrado habitado por la luz.",
    "La gratitud es la llave que abre las puertas del cielo.",
    "Escucho con el corazón los mensajes de mis guías.",
    "Soy paciente conmigo mismo en mi proceso de evolución.",
    "La bondad es mi brújula en todas mis interacciones.",
    "Mi creatividad es un don divino que comparto con alegría.",
    "Hoy atraigo situaciones de paz y armonía.",
    "La protección de los ángeles es mi escudo diario.",
    "Confío en que todo sucede para mi mayor bien.",
    "Mi energía es vibrante, pura y renovada cada mañana.",
    "El universo conspira a mi favor en este momento.",
    "Soy un ser de luz viviendo una experiencia humana.",
    "Mis manos están bendecidas para crear y sanar.",
    "La sabiduría antigua reside en mi alma y me guía.",
    "Hoy elijo la felicidad por encima de cualquier circunstancia.",
    "Los ángeles de la alegría danzan a mi alrededor.",
    "Mi voz es clara y transmite verdades amorosas.",
    "Soy capaz de manifestar mis deseos más puros.",
    "La presencia divina es constante en mi vida.",
    "Aprecio el silencio como un espacio para escuchar a Dios.",
    "Mis relaciones están basadas en el respeto y el amor mutuo.",
    "La abundancia no es solo dinero, es bienestar total.",
    "Soy un servidor de la paz en la Tierra.",
    "La luz de los ángeles me envuelve como un manto cálido.",
    "Hoy recibo noticias maravillosas que esperaba.",
    "Mi propósito de vida se revela con claridad día a día.",
    "Soy valiente para seguir el llamado de mi corazón.",
    "La compasión guía mis actos hacia los demás.",
    "Cada encuentro hoy tiene un propósito divino.",
    "Mis pensamientos son semillas de amor y éxito.",
    "Estoy en perfecta sintonía con el ritmo del universo.",
    "La magia de los ángeles se manifiesta en los detalles cotidianos.",
    "Soy merecedor de amor, éxito y plenitud.",
    "Mi intuición se agudiza cada vez que confío en ella.",
    "La risa es música para los ángeles y para mi alma.",
    "Hoy decreto que todo saldrá mejor de lo esperado.",
    "La serenidad es mi fuerza en momentos de cambio.",
    "Los ángeles del amor fortalecen mi vínculo de pareja.",
    "Soy un canal abierto para la inspiración divina.",
    "Mi camino está pavimentado con pétalos de bendición.",
    "Acepto el flujo de la vida con gracia y facilidad.",
    "El Arcángel Jofiel embellece mis pensamientos and mi entorno.",
    "Soy libre para expresar mi verdadera esencia.",
    "La abundancia infinita me rodea y me sostiene.",
    "Hoy actúo con la certeza de que no estoy solo.",
    "Mis miedos se transforman en fe profunda.",
    "La luz interior brilla con más fuerza cada día.",
    "Soy un ejemplo de paz en un mundo en movimiento.",
    "Los ángeles de la guarda de mis seres queridos los protegen.",
    "Mi mente está abierta a nuevas y maravillosas ideas.",
    "Agradezco por la salud perfecta que fluye en mí.",
    "Hoy atraigo la prosperidad en todas sus formas.",
    "La dulzura de la Virgen y los ángeles me acompaña.",
    "Soy resiliente y capaz de superar cualquier prueba.",
    "Mis palabras sanan y consuelan a quienes las escuchan.",
    "La luz de la verdad ilumina cada rincón de mi ser.",
    "Soy un ser radiante, lleno de vitalidad y energía.",
    "Los ángeles me ayudan a ver la solución, no el problema.",
    "Mi corazón es un jardín de virtudes divinas.",
    "Hoy camino con la elegancia y seguridad de un alma libre.",
    "La armonía reina en mi trabajo y en mis proyectos.",
    "Agradezco por el regalo de la vida y cada nuevo amanecer.",
    "Soy un eslabón importante en la cadena del amor universal.",
    "Los ángeles del consuelo borran mis penas.",
    "Mi fe mueve montañas y atrae milagros.",
    "Hoy decido ser la mejor versión de mí mismo.",
    "La sabiduría de mi ser superior es mi guía.",
    "Soy bendecido con amigos que nutren mi alma.",
    "La luz de Dios me precede y me abre camino.",
    "Acepto la abundancia como mi derecho de nacimiento.",
    "Mis acciones de hoy siembran un futuro de paz.",
    "Los ángeles me enseñan a amarme a mí mismo.",
    "Soy un imán para la buena suerte y la fortuna divina.",
    "La música del cielo resuena en mi interior.",
    "Hoy es el día perfecto para empezar de nuevo.",
    "Confío en los tiempos del universo, son perfectos.",
    "La claridad mental me permite tomar decisiones sabias.",
    "Soy un guerrero de la luz, fuerte y compasivo.",
    "Los ángeles de la paciencia me ayudan a esperar con fe.",
    "Mi entorno es un reflejo de mi paz interior.",
    "Agradezco por los milagros ocultos en mi rutina.",
    "Soy un ser ilimitado conectado con la Fuente.",
    "La presencia del Arcángel Chamuel llena mi vida de amor.",
    "Hoy libero cualquier juicio hacia mí y hacia otros.",
    "Mi bienestar es una prioridad bendecida por el cielo.",
    "Atraigo la armonía a todos mis asuntos legales y trámites.",
    "La luz blanca de protección me rodea 24/7.",
    "Soy humilde para aprender y valiente para enseñar.",
    "Mi alma brilla con la pureza de un cristal divino.",
    "Los ángeles del perdón limpian mi corazón de rencores.",
    "Hoy recibo la guía necesaria para mi proyecto actual.",
    "Confío en que mis necesidades serán cubiertas con creces.",
    "El amor es la respuesta a todas mis preguntas.",
    "Soy un puente de luz entre el cielo y la tierra.",
    "La alegría de vivir se manifiesta en cada una de mis células.",
    "Mis ancestros y ángeles familiares me sostienen.",
    "Hoy elijo pensamientos que me empoderan y elevan.",
    "La belleza del mundo es un recordatorio del amor de Dios.",
    "Soy agradecido por las lecciones que me han hecho fuerte.",
    "Los ángeles de la comunicación facilitan mis diálogos.",
    "Mi mente está en paz, mi cuerpo está relajado.",
    "Atraigo la solución perfecta a cualquier situación compleja.",
    "Soy un creador consciente de mi propia realidad.",
    "La luz de los ángeles brilla en mis ojos.",
    "Hoy experimento una profunda sensación de seguridad.",
    "Mis talentos son dones para servir a la humanidad.",
    "Agradezco por la tecnología que me permite conectar con luz.",
    "Soy un imán para la sabiduría y el conocimiento elevado.",
    "La protección divina es mi herencia constante.",
    "Hoy es un día de sorpresas místicas y hermosas.",
    "Mi fe es el ancla que me sostiene en la tormenta.",
    "Soy merecedor de descanso y renovación profunda.",
    "Los ángeles del éxito acompañan mi carrera profesional.",
    "Mi vida fluye con la suavidad del agua pura.",
    "Hoy bendigo a cada persona con la que interactúo.",
    "La luz de la esperanza arde siempre en mi pecho.",
    "Soy auténtico y mi verdad me hace libre.",
    "Los ángeles me ayudan a organizar mis prioridades.",
    "Mi espíritu es joven, eterno y lleno de energía.",
    "Agradezco por la abundancia de aire, agua y vida.",
    "Soy un sol de amor irradiando calor a mi alrededor.",
    "La guía angélica me lleva al lugar correcto en el momento justo.",
    "Hoy suelto el estrés y acepto la calma divina.",
    "Mis sueños son semillas de realidades maravillosas.",
    "Confío en el poder de la oración y la intención pura.",
    "Soy un recipiente de bendiciones infinitas.",
    "La luz de los arcángeles protege mis viajes y caminos.",
    "Hoy encuentro paz en medio del ruido del mundo.",
    "Mi corazón late al ritmo del amor universal.",
    "Agradezco por la sabiduría de los libros y maestros.",
    "Soy un ser de paz y mi presencia calma a los demás.",
    "Los ángeles de la abundancia abren nuevas puertas hoy.",
    "Mi intuición es mi GPS espiritual de alta precisión.",
    "Hoy celebro la vida con cada pequeño gesto.",
    "Soy digno de recibir grandes milagros hoy mismo.",
    "La luz divina me nutre física y espiritualmente.",
    "Confío en que mis seres queridos están a salvo con Dios.",
    "Mi palabra tiene poder para bendecir y prosperar.",
    "Hoy atraigo situaciones que me hacen sonreír del alma.",
    "La paciencia divina se manifiesta a través de mi calma.",
    "Soy un aprendiz del amor en la escuela de la vida.",
    "Los ángeles del orden traen equilibrio a mi hogar.",
    "Mi mente es un espacio sagrado de pensamientos elevados.",
    "Agradezco por la guía que recibo en mis meditaciones.",
    "Soy un imán para la inspiración artística y creativa.",
    "La protección de San Miguel protege mis redes y comunicaciones.",
    "Hoy actúo con la certeza de que el bien siempre triunfa.",
    "Mi fe es la llave que abre todas las puertas cerradas.",
    "Soy valioso simplemente por ser quien soy.",
    "Los ángeles de la ternura abrazan mi corazón hoy.",
    "Mi vida es un testimonio de la gracia divina.",
    "Hoy fluyo con los cambios con alegría y confianza.",
    "Agradezco por la salud de mis ojos y mi visión.",
    "Soy un canal de paz en mi familia y comunidad.",
    "La luz de los ángeles me guía hacia la prosperidad.",
    "Hoy elijo comer y beber cosas que nutren mi luz.",
    "Confío en que el pasado ha quedado atrás para mi bien.",
    "Mi alma se expande en amor con cada nueva experiencia.",
    "Los ángeles de la justicia velan por la equidad en mi vida.",
    "Soy capaz de transformar el dolor en sabiduría.",
    "La sabiduría del Espíritu Santo ilumina mis decisiones.",
    "Hoy me doy permiso para brillar sin miedos.",
    "Agradezco por el techo sobre mi cabeza y el pan en mi mesa.",
    "Soy un ser vibrante, saludable y lleno de luz.",
    "Los ángeles del trabajo me ayudan a ser productivo y feliz.",
    "Mi intuición me avisa de cualquier peligro y me guía al bien.",
    "Hoy atraigo a mi vida personas de corazón noble.",
    "La paz que sobrepasa todo entendimiento me habita.",
    "Soy bendecido con una mente clara y una memoria ágil.",
    "Agradezco por las oportunidades de servir a los demás.",
    "La caricia de los ángeles se siente en la brisa de hoy.",
    "Hoy decreto que soy libre de toda limitación mental.",
    "Mi cuerpo sana rápidamente bajo la luz de Rafael.",
    "Confío en que lo que es para mí llegará sin esfuerzo.",
    "Soy un faro de luz en medio de cualquier oscuridad.",
    "La alegría divina es mi fortaleza constante.",
    "Los ángeles de la fe fortalecen mis creencias positivas.",
    "Mi vida es una aventura espiritual rica y emocionante.",
    "Hoy encuentro belleza en lo más simple de la naturaleza.",
    "Agradezco por el don de la comunicación y el lenguaje.",
    "Soy un imán para el amor verdadero y duradero.",
    "La luz de los ángeles protege mis finanzas y sustento.",
    "Hoy recibo ideas brillantes para solucionar mis retos.",
    "Mi espíritu es libre como el vuelo de un ángel.",
    "Confío en la sabiduría de mis guías espirituales.",
    "Soy merecedor de toda la felicidad del universo.",
    "Los ángeles de la gratitud elevan mi frecuencia hoy.",
    "Mi hogar es un santuario de paz y amor divino.",
    "Hoy camino con la frente en alto y el alma llena de luz.",
    "Agradezco por la música que eleva mi vibración.",
    "Soy un creador de armonía en todos mis entornos.",
    "La protección divina me acompaña en cada viaje.",
    "Hoy elijo el amor sobre el miedo en cada decisión.",
    "Confío en que estoy siendo guiado hacia mi mayor éxito.",
    "Mi vida está llena de bendiciones inesperadas.",
    "Los ángeles del consuelo sanan mis viejas heridas.",
    "Soy un ser radiante de paz profunda y estabilidad.",
    "Agradezco por la tecnología que me ayuda a crecer.",
    "La luz de los arcángeles ilumina mi propósito.",
    "Hoy soy un imán para la buena voluntad de los demás.",
    "Mi fe es inquebrantable y mi voluntad es fuerte.",
    "Confío en la guía interna que recibo constantemente.",
    "Soy digno de vivir una vida extraordinaria.",
    "Los ángeles de la alegría llenan mi día de risas.",
    "Mi mente está alineada con la sabiduría divina.",
    "Hoy encuentro motivos para agradecer en cada esquina.",
    "Agradezco por la salud perfecta de mis huesos y cuerpo.",
    "Soy un canal de luz para la sanación del planeta.",
    "La protección de los ángeles es mi herencia divina.",
    "Hoy recibo bendiciones que multiplican mi bienestar.",
    "Confío en el proceso de la vida y su flujo natural.",
    "Mi corazón es un imán para el amor incondicional.",
    "Los ángeles de la perseverancia me ayudan a seguir adelante.",
    "Soy un ser de luz, amado y protegido siempre.",
    "Agradezco por la belleza del sol y la luna.",
    "La paz de los ángeles reina en mis relaciones.",
    "Hoy decreto abundancia infinita para mí y para todos.",
    "Confío en que el universo me provee de todo bien.",
    "Mi alma está en paz con su destino divino.",
    "Los ángeles de la creatividad inspiran mis proyectos.",
    "Soy un imán para la paz y la tranquilidad mental.",
    "Agradezco por la vida y todas sus maravillosas formas.",
    "La luz divina me envuelve en un abrazo eterno.",
    "Hoy atraigo soluciones mágicas a mis problemas.",
    "Confío en la bondad intrínseca de la vida.",
    "Mi mente es un imán para pensamientos positivos.",
    "Los ángeles del perdón me liberan de toda culpa.",
    "Soy un ser sagrado viviendo una experiencia gloriosa.",
    "Agradezco por el regalo de la amistad sincera.",
    "La protección de los arcángeles es total y absoluta.",
    "Hoy irradio amor y recibo amor en abundancia.",
    "Confío en que mis ángeles trabajan a mi favor.",
    "Mi camino está bendecido con luz y claridad.",
    "Los ángeles de la felicidad me acompañan hoy.",
    "Soy merecedor de paz profunda y duradera.",
    "Agradezco por la salud y vitalidad de mi cuerpo.",
    "La luz de los ángeles brilla en cada uno de mis actos.",
    "Hoy es un día de milagros y bendiciones celestiales.",
    "Confío en la perfecta orquestación del universo.",
    "Mi vida es un jardín de posibilidades infinitas.",
    "Los ángeles del amor guían mis relaciones hoy.",
    "Soy un imán para la prosperidad y el éxito.",
    "Agradezco por el aire puro y la naturaleza.",
    "La protección divina me rodea y me sostiene.",
    "Hoy encuentro armonía en todo lo que hago.",
    "Confío en que soy guiado por la voluntad divina.",
    "Mi alma canta de alegría por estar viva.",
    "Los ángeles de la paz calman mis pensamientos.",
    "Soy un canal de amor puro para la humanidad.",
    "Agradezco por las bendiciones que aún están por llegar.",
    "La luz de Dios me protege en todo momento.",
    "Hoy atraigo solo lo mejor a mi realidad.",
    "Confío en que el amor divino lo cura todo.",
    "Mi mente es un remanso de paz y sabiduría.",
    "Los ángeles de la abundancia me bendicen hoy.",
    "Soy un ser de luz infinita y poder divino.",
    "Agradezco por la sabiduría que los ángeles me dan.",
    "La protección de los arcángeles es mi seguridad diaria.",
    "Hoy celebro la magia de existir en este momento.",
    "Confío en que la luz siempre guía mis pasos.",
    "Mi vida es una bendición continua del cielo.",
    "Los ángeles de la guarda velan por mi bienestar.",
    "Soy merecedor de todo el bien que el universo ofrece.",
    "Agradezco por la paz que habita en mi corazón.",
    "La luz suprema ilumina mi camino hacia la verdad.",
    "Hoy soy un imán para la felicidad y el amor.",
    "Confío en el poder sanador de los ángeles.",
    "Mi espíritu es fuerte, radiante y eterno.",
    "Los ángeles de la fe me sostienen en todo momento.",
    "Soy un ser amado por todo el reino celestial.",
    "Agradezco por cada bendición que recibo hoy.",
    "La protección divina es mi escudo inquebrantable.",
    "Hoy actúo con la certeza de ser guiado por Dios.",
    "Confío en que mi vida está en manos de los ángeles.",
    "Mi corazón rebosa de gratitud y amor puro.",
    "Los ángeles de la alegría iluminan mi día por completo.",
    "Soy un faro de luz para todos los que me rodean.",
    "Agradezco por la armonía y la paz en mi vida.",
    "La luz de los arcángeles me rodea hoy y siempre.",
    "Hoy es un gran día para recibir milagros inesperados.",
    "Confío en la infinita bondad del universo divino.",
    "Mi alma es una chispa divina de luz y amor eternos.",
    "Los ángeles me guían hacia mi más alto destino.",
    "Soy libre de todo miedo y lleno de fe divina.",
    "Agradezco por la protección constante de mis guías.",
    "La luz de los ángeles es mi guía en la oscuridad.",
    "Hoy elijo la paz y el amor como mi camino.",
    "Confío en que todo está bien en mi mundo divino.",
    "Mi vida es un reflejo de la gloria celestial.",
    "Los ángeles me aman y me apoyan en cada paso.",
    "Soy un ser bendecido, próspero y muy feliz.",
    "Agradezco por la guía amorosa de mis ángeles hoy."
];

const invocations = [
    "Arcángel Miguel, protégeme con tu espada de luz y valor.",
    "Arcángel Rafael, sana cada fibra de mi ser con tu rayo verde.",
    "Arcángel Gabriel, trae claridad y propósito a mis palabras.",
    "Arcángel Uriel, ilumina mi mente con sabiduría y abundancia.",
    "Arcángel Chamuel, llena mi vida y mis relaciones de amor puro.",
    "Arcángel Jofiel, embellece mis pensamientos y mi entorno hoy.",
    "Arcángel Zadquiel, transmuta todo dolor en alegría y perdón.",
    "Ángeles de la guarda, guíen mis pasos por caminos de paz.",
    "Coros celestiales, eleven mi vibración hacia la armonía divina.",
    "Legiones de luz, despejen cualquier obstáculo en mi misión.",
    "Presencia divina, manifiéstame la magia de los milagros hoy.",
    "Seraphines ardientes, enciendan el fuego del amor en mi alma."
];

const prayers = [
    "Amado Ángel de mi guarda, no me desampares ni de noche ni de día.",
    "Padre celestial, gracias por enviar a tus ángeles a cuidarme.",
    "Oración por la paz: Que la luz angélica calme todo conflicto en mí.",
    "Gratitud infinita: Gracias ángeles por las bendiciones recibidas.",
    "Pedido de guía: Muéstrenme el camino derecho hacia mi felicidad.",
    "Oración por la salud: Rafael, restaura mi energía y vitalidad.",
    "Protección del hogar: Miguel, sella mi casa con tu luz azul.",
    "Abundancia divina: Uriel, abre las puertas de la prosperidad hoy.",
    "Sanación emocional: Chamuel, sana mis heridas y enséñame a amar.",
    "Claridad espiritual: Gabriel, despierta mi intuición suprema.",
    "Perdón sagrado: Zadquiel, ayúdame a soltar el pasado con amor.",
    "Bendición diaria: Que los ángeles acompañen cada uno de mis actos."
];

const meditations = [
    "Respira luz blanca: Siente cómo la paz de los ángeles te inunda.",
    "Visualiza alas doradas: Estás protegido y sostenido por el cielo.",
    "Caminata en las nubes: Imagina que caminas junto a tu guía celestial.",
    "El templo del corazón: Entra en tu interior y encuentra a tus ángeles.",
    "Baño de luz verde: Rafael te envuelve en una esfera de sanación.",
    "Escucha el silencio: En el vacío espiritual, los ángeles te hablan.",
    "Conexión con la tierra: Siente el apoyo de los ángeles de la naturaleza.",
    "Vuelo de libertad: Imagina que tu alma se eleva con ligereza divina.",
    "Rayos de colores: Deja que cada arcángel te bañe con su energía propia.",
    "Anclaje de luz: Eres un canal de energía celestial hacia la tierra.",
    "Abrazo angélico: Siente el calor y la seguridad de ser amado.",
    "Gratitud profunda: Medita en las infinitas razones para sonreír hoy."
];

const reflections = [
    "El silencio no es vacío, es el espacio donde los ángeles te susurran la verdad.",
    "Cada lágrima es una oración que el cielo recoge para transformarla en sabiduría.",
    "Tu luz interior es tan potente que puede iluminar el camino de miles; no la apagues.",
    "Aceptar tu vulnerabilidad es el primer paso para descubrir tu verdadera fortaleza divina.",
    "El universo no te quita cosas, solo te libera de lo que ya no sirve para tu evolución.",
    "La paz no es la ausencia de caos, sino la presencia de Dios en medio de la tormenta.",
    "Eres un milagro caminando; nunca olvides la magia que reside en tu propia existencia.",
    "Cuando sueltas el control, permites que la mano de los ángeles orqueste tu destino.",
    "Tu pasado fue una escuela, no una sentencia de cadena perpetua; hoy eres libre.",
    "La gratitud es la frecuencia más alta; cuando agradeces, el cielo se abre ante ti.",
    "No busques respuestas afuera; la brújula angélica está instalada en tu corazón.",
    "Cada encuentro es sagrado; trata a todos como si fueran ángeles disfrazados."
];

const frequencies = [
    { name: "Frecuencia 1 - Sanación", url: "https://www.youtube.com/embed/oaFK5VvPLd4?si=XDw0ycxyjRlsU3PQ" },
    { name: "Frecuencia 2 - Elevación", url: "https://www.youtube.com/embed/EEpIZVPHGFE?si=Ybjg1juwdzrFZVuZ" },
    { name: "Frecuencia 3 - Paz Interior", url: "https://www.youtube.com/embed/oaFK5VvPLd4?si=XDw0ycxyjRlsU3PQ" },
    { name: "Frecuencia 4 - Conexión", url: "https://www.youtube.com/embed/EEpIZVPHGFE?si=Ybjg1juwdzrFZVuZ" },
    { name: "Frecuencia 5 - Abundancia", url: "https://www.youtube.com/embed/oaFK5VvPLd4?si=XDw0ycxyjRlsU3PQ" }
];

const data = {
    affirmations,
    invocations,
    prayers,
    meditations,
    reflections,
    frequencies
};
